name: my-first-github-action
on: 
  push:
    branches-ignore:
     - trying
     - staging
  
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g bats
      - run: bats -v
  test-env-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: |
          echo "MAILU_VERSION=$(GITHUB_REF#refs/heads/) | sed 's/\//_/g'" >> $GITHUB_ENV
          echo "TRAVIS_BRANCH=${GITHUB_REF#refs/heads/) | sed 's/\//_/g'" >> $GITHUB_ENV         
      - name: test some env vars
        env:
          TEST: ${{ env.MAILU_VERSION }}
        run: |
          echo github.event.number = ${{ github.event.number  }}
          echo github.event.pull_request.number = ${{ github.event.pull_request.number }}
          echo github.event.issue.number = ${{ github.event.issue.number }}
          echo MAILU_VERSION = $(MAILU_VERSION)
          echo TEST = $(TEST)          
          echo TRAVIS_BRANCH = $(TRAVIS_BRANCH)
          
          
 
