name: my-first-github-action
on: 
  push:
    branches-ignore:
     - trying
     - staging
  
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g bats
      - run: bats -v
  test-env-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: |
          echo "::set-env name=MAILU_VERSION::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
          echo "::set-env name=TRAVIS_BRANCH::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"     
      - name: test some env vars
        run: |
          echo github.event.number = ${{ github.event.number  }}
          echo github.event.pull_request.number = ${{ github.event.pull_request.number }}
          echo github.event.issue.number = ${{ github.event.issue.number }}
          echo MAILU_VERSION = ${MAILU_VERSION}
          echo TRAVIS_BRANCH = ${TRAVIS_BRANCH}
